import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UMAX Dashboard",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <head>
        <link
          rel="icon"
          href="/assets/icon.png"
        />
      </head> 
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}

